### ISSUE TITLE
Is this project open-source?

### ISSUE THREAD

**Issue by CaledoniaProject** [microsoft/ipe#1]
There's no source code or binary release in this repo, how can I obtain them?

**Comment by tobiasoort** [comment]
The project is currently in Request-for-comment phase. The license is MIT.

From the FAQ:
Where can I find the code for IPE?
The IPE LSM code has been submitted for review to the Linux kernel project: https://lkml.kernel.org/lkml/20200406221439.1469862-4-deven.desai@linux.microsoft.com/T/#mfe85eb38a5596999f0bb8aa9dda3bee4e71eaa60

**Comment by CaledoniaProject** [comment]
OK, Thanks
