### ISSUE TITLE
Technical diagrams missing

### ISSUE THREAD

**Issue by evelynmitchell** [microsoft/ipe#3]

**Comment by bowerscd** [comment]
Thanks. I've fixed it as of 55977a126f129391d8ac3e99086decf736ffa7e3.

**Comment by evelynmitchell** [comment]
The diagrams are at ipe/docs/assets/diagrams/ but the description at ipe/blob/master/docs/technical/diagrams.md refers to /ipe/assets/diagrams/

**Comment by bowerscd** [comment]
This is because of [mkdocs](https://microsoft.github.io/ipe/attribution/) - it generates a whole tree from the content under `/docs`, and then creates the static site that we use for github pages. (The gh-pages drops everything outside of `/docs` and it effectively becomes the new root.
